# Change these first
owner: mad-hengseyha # Your GitHub organization or username, where this repository lives
repo: hungry-app-status # The name of this repository

sites:
  - name: HungryApp Backend
    url: $BASE_URL
    icon: https://assets.website-files.com/615a7301656c0a8be70fc9b1/620dcb90a7f4744361044a28_hungryapp-secondary-logo-no-border-01.svg
  - name: HungryApp API
    url: $API_URL?consumer_key=$API_CONSUMER_KEY&consumer_secret=$API_SECRET_KEY
    icon: https://assets.website-files.com/615a7301656c0a8be70fc9b1/620dcb90a7f4744361044a28_hungryapp-secondary-logo-no-border-01.svg
#   - name: HungryApp Mobile Application
#     url: $HUNGRY_APP_SECRET_URL?consumer_key=$API_CONSUMER_KEY&consumer_secret=$API_SECRET_KEY
#     icon: https://assets.website-files.com/615a7301656c0a8be70fc9b1/620dcb90a7f4744361044a28_hungryapp-secondary-logo-no-border-01.svg

# Schedul mantenaince
# start: 2021-02-24T13:00:00.220Z
# end: 2021-02-24T14:00:00.220Z
# expectedDown: HUNGRY APP ADMIN, HUNGRY APP API

user-agent: mad-hengseyha

assignees:
    - mad-hengseyha

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hungryapp.asia
#   baseUrl: /hungry-app-status
  logoUrl: https://assets.website-files.com/615a7301656c0a8be70fc9b1/620dcb90a7f4744361044a28_hungryapp-secondary-logo-no-border-01.svg
  name: HUNGRY APP Status
  introTitle: "**HungryApp.** Delivering happiness."
  introMessage: Track all HungryApp performances in one place. View the status of the backend and API here!
  navbar:
    - title: Status
      href: /
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: © HUNGRY APP
